# Generated by Django 4.0.6 on 2022-09-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='place',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
