# Generated by Django 4.0.6 on 2022-10-15 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_supermarketproduct_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=20)),
                ('serves', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductInRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='list.product')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.recipe')),
            ],
        ),
    ]
